#pragma once

#define ERR_OPENING_FILE -1
#define ERR_GETING_ROWS_COLS_SIZE -2
#define ERR_MATRIX_ALOCATION -3
#define ERR_NOT_ENOUGHT_DATA_IN_MATRIX_FILE -4
#define ERR_MATRIX_MULTIPLICATION -5
#define ERR_RESULT_ARRAY_TO_FILE -6